Refactor workflows to avoid > 3 nested levels

diff --git a/.github/workflows/spring-artifactory-release.yml b/.github/workflows/spring-artifactory-release.yml
--- a/.github/workflows/spring-artifactory-release.yml
+++ b/.github/workflows/spring-artifactory-release.yml
@@ -11,24 +11,50 @@ on:
         description: 'Additional Maven or Gradle command arguments: tasks, goals, plugins etc. The `install` for Maven is included. The `build` and `artifactoryPublish` for Gradle are included.'
         required: false
         type: string
-      repositoryTeam:
-        description: 'Comma-separate GitHub user names for repository team members to exclude from contributors'
-        required: false
-        type: string
 
 jobs:
+  releaseVersion:
+    runs-on: ubuntu-latest
+    outputs:
+      releaseVersion: ${{ steps.release-version.outputs.releaseVersion }}
+
+    steps:
+
+      - uses: actions/checkout@v4
+        with:
+          show-progress: false
+
+      - name: Find Current Version to Release
+        id: release-version
+        run: |
+          if test -f pom.xml
+          then
+            CURRENT_VERSION=$(./mvnw help:evaluate -Dexpression="project.version" -q -DforceStdout)
+          else
+            CURRENT_VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
+          fi
+          export CANDIDATE_VERSION=${CURRENT_VERSION/-SNAPSHOT}
+          RELEASE_VERSION=$(gh api repos/$GITHUB_REPOSITORY/milestones --jq 'map(select(.title | startswith(env.CANDIDATE_VERSION))) | .[0] | .title')
+          if [ -z $RELEASE_VERSION ]; then
+            echo "::error::No scheduled milestone for $CURRENT_VERSION version."
+            exit 1
+          fi
+          echo releaseVersion=$RELEASE_VERSION >> $GITHUB_OUTPUT
+          echo "::notice::RELEASE VERSION=$RELEASE_VERSION"
+
   staging:
+    needs: releaseVersion
     uses: spring-projects/spring-integration-aws/.github/workflows/spring-stage-release.yml@main
     with:
-      releaseVersion: ${{ inputs.releaseVersion }}
+      releaseVersion: ${{ needs.releaseVersion.outputs.releaseVersion }}
       buildToolArgs: ${{ inputs.buildToolArgs }}
     secrets: inherit
 
   verify-staged:
-    needs: staging
+    needs: [releaseVersion, staging]
     uses: ./.github/workflows/verify-staged-artifacts.yml
     with:
-      releaseVersion: ${{ inputs.releaseVersion }}
+      releaseVersion: ${{ needs.releaseVersion.outputs.releaseVersion }}
     secrets: inherit
 
   promote-milestone:
@@ -51,9 +77,8 @@ jobs:
 
   finalize:
     if: ${{ !(failure() || cancelled()) }}
-    needs: [promote-milestone, promote-ga]
+    needs: [releaseVersion, promote-milestone, promote-ga]
     uses: spring-projects/spring-integration-aws/.github/workflows/spring-finalize-release.yml@main
     with:
-      milestone: ${{ inputs.releaseVersion }}
-      repositoryTeam: ${{ inputs.repositoryTeam }}
+      milestone: ${{ needs.releaseVersion.outputs.releaseVersion }}
     secrets: inherit
